services:
    blitze.autodbrestore.config:
        class: blitze\autodbrestore\services\config
        arguments:
            - '@filesystem'
            - '%core.root_path%'
            - '%core.root_path%ext/blitze/autodbrestore/config.%core.php_ext%'

    blitze.autodbrestore.restorer:
        class: blitze\autodbrestore\services\restorer
        arguments:
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'

    blitze.autodbrestore.cron.task.restore:
        class: blitze\autodbrestore\cron\task\restore
        arguments:
            - '@cache.driver'
            - '@log'
            - '@user'
            - '@blitze.autodbrestore.config'
            - '@blitze.autodbrestore.restorer'
        calls:
            - [set_name, [blitze.autodbrestore.cron.task.restore]]
        tags:
            - { name: cron.task }

    blitze.autodbrestore.event.listener:
        class: blitze\autodbrestore\event\listener
        arguments:
            - '@language'
            - '@template'
            - '@blitze.autodbrestore.config'
        tags:
            - { name: event.listener }
